### ISSUE TITLE
The program abort execution on Mac OS

### ISSUE THREAD

**Issue by bztia** [dennisguse/ITU-T_pesq#2]
The error msg is:
[1]    22822 abort      ./pesq_darwin +16000 /Users/xxx//mos/wave.wav

**Comment by dennisguse** [comment]
Which compiler did you use?

**Comment by bztia** [comment]
> Which compiler did you use?
cc --version
Apple LLVM version 10.0.1 (clang-1001.0.46.3)
Target: x86_64-apple-darwin18.2.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

I rerun it in bash instead of zsh to see the error msg
It's "Abort trap: 6", the error code returned is -6. 

It seems file name related, it occurs when I use ./w.wav or use long full name with '/' in it

**Comment by bztia** [comment]
Seems below code will cause the SIGABRT:
strcpy (ref_info. file_name, 1 + strrchr (ref_info. file_name, ...
The src and dst are pointing to same memory.
Alloc another buffer to avoid this issue:

```C
            char * file_name = NULL;
            
            file_name = ref_info. path_name;
            if (strrchr (file_name, '\\') != NULL) {
                file_name = 1 + strrchr (file_name, '\\');
            }
            if (strrchr (file_name, '/') != NULL) {
                file_name = 1 + strrchr (file_name, '/');
            }
            strcpy (ref_info. file_name, file_name);

            file_name = deg_info. path_name;
            if (strrchr (file_name, '\\') != NULL) {
                file_name = 1 + strrchr (file_name, '\\');
            }
            if (strrchr (file_name, '/') != NULL) {
                file_name = 1 + strrchr (file_name, '/');
            }
            strcpy (deg_info. file_name, file_name);         
```

**Comment by dennisguse** [comment]
Did you change the code? And would you mind submitting a pull request?

**Comment by bztia** [comment]
> Did you change the code? And would you mind submitting a pull request?

OK, I revised my change and sent a pull request.
